[tools]
taplo = "latest"
prettier = "latest"

[tasks.format]
run = [
  "fish_indent -w .fish/config.fish .fish/conf.d/*.fish .fish/functions/*.fish",
  "taplo format .mise/config.toml mise.toml",
  "prettier --write .hyper.js .ccstatusline/settings.json .claude/settings.json .docker/config.json .karabiner/karabiner.json .vscode/settings.json",
]
